/** All currencies quoted by the bundled Bank of Taiwan history. */
export const CURRENCY_OPTIONS: Array<[string, string]> = [
  ['TWD', 'TWD 新臺幣'],
  ['USD', 'USD 美元'],
  ['EUR', 'EUR 歐元'],
  ['JPY', 'JPY 日圓'],
  ['GBP', 'GBP 英鎊'],
  ['CNY', 'CNY 人民幣'],
  ['HKD', 'HKD 港幣'],
  ['SGD', 'SGD 新加坡幣'],
  ['KRW', 'KRW 韓元'],
  ['AUD', 'AUD 澳幣'],
  ['CAD', 'CAD 加拿大幣'],
  ['CHF', 'CHF 瑞士法郎'],
  ['NZD', 'NZD 紐西蘭幣'],
  ['THB', 'THB 泰銖'],
  ['PHP', 'PHP 菲律賓披索'],
  ['IDR', 'IDR 印尼盾'],
  ['VND', 'VND 越南盾'],
  ['MYR', 'MYR 馬來幣'],
  ['SEK', 'SEK 瑞典幣'],
  ['ZAR', 'ZAR 南非幣'],
  ['OTHER', '其他幣別'],
];
